PATCH http://localhost:5071/group/5922159b-2b26-46d4-8726-288e2a3f5b75
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlMWNkYjZkMS1iNzU2LTRkNzAtOWE0Yi1mY2M4ZjY3MmZiZmMiLCJuYW1lIjoiYWxleGFuZGVyIiwiZW1haWwiOiJhbGV4YW5kZXJAZ21haWwuY29tIiwic3ViIjoiOTNmNTIwOTQtMjIyNS00ODRlLWJiYTktMGJiNjBiOTJkYjM3IiwiZXhwIjoxNzEzNjQ0NTIyLCJpc3MiOiJTY2hlZHVsZXIiLCJhdWQiOiJTY2hlZHVsZXIifQ.ezM5zeckI1-5w_XlSbfyqm-M8eTw3CKAwSnvq7Dk8Ac

{
    "groupName": "group1"
}